name: deploy HTML to s3
on: push
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCES_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCES_KEY }}
          aws-region: us-east-1
      - name: Code satic code to S3
        run: |
          aws s3 sync . s3://githubactions-static-website-demo/ \
          --exclude "*" \
          --include "index.html"
